version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true  # Ensure that existing files are overwritten
hooks:
  BeforeStart:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root